[build]
# Uncomment the relevant target for your chip here (ESP32, ESP32-S2, ESP32-S3 or ESP32-C3)
{% if mcu != "esp32" %}#{% endif %}target = "xtensa-esp32-espidf"
{% if mcu != "esp32s2" %}#{% endif %}target = "xtensa-esp32s2-espidf"
{% if mcu != "esp32s3" %}#{% endif %}target = "xtensa-esp32s3-espidf"
{% if mcu != "esp32c6" %}#{% endif %}target = "riscv32imac-esp-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash --monitor"
rustflags = ["--cfg", "espidf_time64"]

[target.xtensa-esp32s2-espidf]
linker = "ldproxy"
runner = "espflash --monitor"
rustflags = ["--cfg", "espidf_time64"]

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "espflash --monitor"
rustflags = ["--cfg", "espidf_time64"]

[target.riscv32imac-esp-espidf]
linker = "ldproxy"
runner = "espflash --monitor"
rustflags = ["--cfg", "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]
